name: Download Universal APK

on:
  workflow_dispatch:
    inputs:
      package_name:
        description: 'Package Name (e.g. com.whatsapp, com.spotify.music)'
        required: true
        default: 'com.whatsapp'

jobs:
  download-apk:
    runs-on: ubuntu-latest

    steps:
      - name: Create output directory
        run: mkdir -p ./apks

      - name: Download apkeep
        run: |
          curl -L -o apkeep https://github.com/EFForg/apkeep/releases/latest/download/apkeep-x86_64-unknown-linux-gnu
          chmod +x apkeep

      - name: Download Full Universal APK
        run: |
          ./apkeep -a "${{ github.event.inputs.package_name }}" \
                   -d apk-pure \
                   -o "arch=arm64-v8a;armeabi-v7a;armeabi;x86;x86_64" \
                   ./apks

      - name: Upload APK as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.inputs.package_name }}-universal
          path: ./apks/*
